# If true, when the role provisions vlans, it will remove extraneous vlans that are present in the configuration but haven't been specified in your host variables.
eos_purge_vlans: true

# Enable or disable purging of Vlan to VNI mappings that are not defined in the vxlan_vlans object.
eos_purge_vxlan: true

# provider is required for arista.eos-* modules.
provider:
  host: '{{ inventory_hostname }}'
  username: admin
  password: arista
  authorize: true
  use_ssl: yes
  transport: eapi
  validate_certs: false

# used for eapi connections
eos_api:
  host: '{{ inventory_hostname }}'
  username: admin
  password: arista
  authorize: true
  use_ssl: yes
  transport: eapi
  validate_certs: false

# used for enabling eapi
eos_cli:
  host: '{{ inventory_hostname }}'
  username: admin
  password: arista
  authorize: true
  transport: cli

ip_domain_name: arista.lab

route_static_default_nexthop: 192.168.50.1

ip_name_server: 192.168.50.1

config_prefix: ls

