---
  - block: 
    - name: "[Prod] eAPI"
      eos_eapi:
        http: no
        state: started
        provider: "{{ eos_cli }}"

    - name: "[Prod] hecking to see if eAPI is online"
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 443
        delay: 2
        state: started
        timeout: 10

    - name: "[Prod] Performing generic configuration"
      eos_config:
        src: generic.j2
        provider: "{{ eos_api }}"
        
    when: production is defined

  - block: 
    - name: "[Test] Peforming initial file cleanup"
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "configs/{{ inventory_hostname }}/{{ inventory_hostname }}.config"

    - name: "[Test] Creating required directories"
      file:
        path: "configs/{{ inventory_hostname }}/"
        state: directory

    - name: "[Test] Generating Configuration Files"
      local_action: template
      args:
        src: generic.j2
        dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_global.config"

    when: test is defined