---

- name: eAPI
  eos_eapi:
    http: no
    state: started
    provider: "{{ eos_cli }}"

- name: Checking to see if eAPI is online
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    delay: 2
    state: started
    timeout: 10

- name: Configuring AAA
  eos_config:
    lines:
      - username admin privilege 15 role network-admin secret 5 {{ admin_secret }}
      - username admin sshkey ssh-rsa {{ admin_sshkey }}
    provider: "{{ eos_api }}"

- name: Configuring DNS and Time
  eos_config:
    lines:
     - ip name-server vrf default 8.8.8.8
     - clock timezone CST6CDT
     - ntp server pool.ntp.org
     - ip domain-name {{ ip_domain_name }}
    provider: "{{ eos_api }}"

- name: Disabling scheduled tech-support (remove this for production)
  eos_config:
    lines:
     - no schedule tech-support
    provider: "{{ eos_api }}"

- name: Configuring a default route
  eos_config:
    lines:
     - ip route 0.0.0.0/0 {{ route_static_default_nexthop }}
    provider: "{{ eos_api }}"

- name: Enabling VMware tools
  eos_config:
    lines:
     - trigger on-boot
     - action bash sudo systemctl start vmtoolsd.service
     - delay 0
    parents: event-handler vmware-tools