---
- name: Configuring CVX
  eos_config:
    src: cvx.j2
    provider: "{{ eos_api }}"

- name: Configuring VXLAN mapping
  eos_config:
    src: vxlan.j2
    provider: "{{ eos_api }}"
  tags: vxlan

- name: Configuring IP Interfaces
  eos_config:
    src: ip_interfaces.j2
    provider: "{{ eos_api }}"
  tags: leaf_interfaces

- name: Configuring VLANs
  eos_config:
    src: vlans.j2
    provider: "{{ eos_api }}"
  tags: leaf_vlans

- name: Configuring MLAG
  eos_config:
    src: mlag.j2
    provider: "{{ eos_api }}"

- name: Configuring L2 Interfaces
  eos_config:
    src: l2_interfaces.j2
    provider: "{{ eos_api }}"
  tags: l2_interfaces

- name: Configuring Port-Channel Interfaces
  eos_config:
    src: po_interfaces.j2
    provider: "{{ eos_api }}"
  tags: po_interfaces

- name: Configuring Loopback Interfaces
  eos_config:
    src: lo_interfaces.j2
    provider: "{{ eos_api }}"
  tags: lo_interfaces

- name: Configuring VLAN Interfaces
  eos_config:
    src: vlan_interfaces.j2
    provider: "{{ eos_api }}"
  tags: vlan_interfaces

- name: Configuring BGP
  eos_config:
    src: leaf_bgp.j2
    provider: "{{ eos_api }}"
  tags: leaf_bgp

