---

- name: Configuring CVX
  eos_config:
    lines:
     - server host {{ cvx_ip }}
     - source-interface Management1
     - no shutdown
    parents: management cvx
    match: strict
    before: no management cvx
    provider: "{{ eos_api }}"

# TODO: Seems like match always thinks there's a change. Why?

- name: Configuring VXLAN mapping
  eos_config:
    src: vxlan.j2
    provider: "{{ eos_api }}"
    before: no interface Vxlan1 # Required for VXLAN>VNI Idempotency
  tags: vxlan

- name: Creating VXLAN Interface
  eos_config:
    lines:
     - vxlan source-interface Loopback1
     - vxlan controller-client
     - vxlan udp-port 4789
    parents: interface Vxlan1
    provider: "{{ eos_api }}"

- name: Configuring Virtual Router MAC
  eos_config:
    lines:
     - ip virtual-router mac-address {{ virtual_router_mac_address }}
    provider: "{{ eos_api }}"

- name: Configuring IP Interfaces
  eos_config:
    src: ip_interfaces.j2
    provider: "{{ eos_api }}"
  tags: leaf_interfaces

- name: Configuring VLANs
  eos_config:
    src: vlans.j2
    provider: "{{ eos_api }}"
  tags: leaf_vlans

- name: Creating MLAG VLAN (4094)
  eos_config:
    lines:
     - trunk group mlagpeer
    parents: vlan 4094
    provider: "{{ eos_api }}"

- name: Disabling Spanning Tree on MLAG VLAN
  eos_config:
    lines:
     - no spanning-tree vlan 4094
    provider: "{{ eos_api }}"

- name: Creating MLAG SVI
  eos_config:
    lines:
     - ip address {{ svi_mlag }}
    parents: interface Vlan4094
    provider: "{{ eos_api }}"

- name: Creating MLAG Peer-Link
  eos_config:
    lines:
     - switchport mode trunk
     - switchport trunk group mlagpeer
    parents: interface port-channel 1
    provider: "{{ eos_api }}"

- name: Adding interfaces into MLAG Peer-Link
  eos_config:
    src: mlag_interfaces.j2
    provider: "{{ eos_api }}"

- name: Setting MLAG configuration
  eos_config:
    lines:
     - domain-id {{ mlag_domain_id }}
     - local-interface Vlan4094
     - peer-address {{ mlag_peer_address }}
     - peer-link Port-Channel1
    parents: mlag configuration
    provider: "{{ eos_api }}"