---
  - block: 
    - name: "[PROD] Pushing Leaf Configuration"
      eos_config:
        src: leaf.j2
        provider: "{{ eos_api }}"

    when: production is defined

  - block: 
    - name: "[Test] Generating Leaf Configuration"
      local_action: template
      args:
        src: leaf.j2
        dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_leaf.config"

    - name: "[Test] Combining Configuration Files"
      assemble:
        src: "configs/{{ inventory_hostname }}/"
        dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}.config"

    - name: "[Test] Peforming file cleanup"
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_leaf.config"
        - "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_global.config"

    when: test is defined