hostname: spine2

bgp:
   as_local: 65001
   router_id: 10.254.254.52
   leaf:
      - 10.2.1.11
      - 10.2.1.21
      - 10.2.2.11
      - 10.2.2.21
      - 10.2.3.11
      - 10.2.3.21

lo_interfaces:
  - name: Loopback0
    description: BGP RID
    address: 10.254.254.52/32

ip_interfaces:
  - name: Ethernet1
    description: leaf1:e2:p2p
    address: 10.2.1.10/31
    state: present
    mtu: 9214
  - name: Ethernet2
    description: leaf2:e2:p2p
    address: 10.2.1.20/31
    state: present
    mtu: 9214
  - name: Ethernet3
    description: leaf3:e2:p2p
    address: 10.2.2.10/31
    state: present
    mtu: 9214
  - name: Ethernet4
    description: leaf4:e2:p2p
    address: 10.2.3.20/31
    state: present
    mtu: 9214
  - name: Ethernet5
    description: leaf5:e2:p2p
    address: 10.2.3.10/31
    state: present
    mtu: 9214
  - name: Ethernet6
    description: leaf6:e2:p2p
    address: 10.2.3.20/31
    state: present
    mtu: 9214